### ISSUE TITLE
Throttle broken with update

### ISSUE THREAD

**Issue by ac1dburnz** [stickz/rtorrent#20]
### Please complete the following tasks.

- [X] Name of seedbox provider or self hosted service
- [X] rTorrent Commit and OS version provided

### Tell us about your environment

5.1  on Debian bookworm 12 

### Tell us if rTorrent seedbox is self hosted or provided

self hosted

### Describe the bug

When updating to 5.1, the throttle plugin no longer loads. After downgrading back down throttle works again. 

### Steps to reproduce

update to 5.1

### Expected behavior

throttle plugin works 

### Additional context

root@rutorrent:~# php /var/www/rutorrent/php/initplugins.php
PHP Warning:  filemtime(): stat failed for /var/www/rutorrent/share/settings/rss/cache/info in /var/www/rutorrent/php/cache.php on line 32

**Comment by stickz** [comment]
All fixed and retagged. Thanks for the heads up!

**Comment by ac1dburnz** [comment]
it works :) thanks for the fast fix.
