### ISSUE TITLE
libtorrent with udns(autoconf issue)

### ISSUE THREAD

**Issue by colinhd8** [stickz/rtorrent#30]
### Please complete the following tasks.

- [X] Name of seedbox provider or self hosted service
- [X] rTorrent Commit and OS version provided

### Tell us about your environment

rTorrent Commit: master acadc5829650eccc9fba4149d2471493fdb91e11
OS: Ubuntu 22.04 LTS

### Tell us if rTorrent seedbox is self hosted or provided

self hosted

### Describe the bug

I'm not familiar with autoconf, but it seems that TORRENT_WITH_UDNS should be added to configure.ac in order to let libtorrent use udns

**Comment by stickz** [comment]
Good catch! This is all fixed now up. I can confirm `-ludns` is added to the build.

**Comment by colinhd8** [comment]
Thank you for the quick fix!
