### ISSUE TITLE
unable to use use_udp_trackers

### ISSUE THREAD

**Issue by ac1dburnz** [stickz/rtorrent#31]
### Please complete the following tasks.

- [X] Name of seedbox provider or self hosted service
- [X] rTorrent Commit and OS version provided

### Tell us about your environment

Debian Bookworm 

### Tell us if rTorrent seedbox is self hosted or provided

n/a

### Describe the bug

Issues when adding use_udp_trackers to .rtorrent.rc. 

rtorrent: Error in option file: ~/.rtorrent.rc:82: Command "use_udp_trackers" does not exist.

### Steps to reproduce

# Set whetever the client should try to connect to UDP trackers.
use_udp_trackers = yes

### Expected behavior

use_udp_trackers works as an option

**Comment by stickz** [comment]
This option is incorrect. The correct value is: `trackers.use_udp.set = yes`.
