### ISSUE TITLE
rTorrent will not run after compiling

### ISSUE THREAD

**Issue by jazha** [stickz/rtorrent#44]
### Please complete the following tasks.

- [X] Name of seedbox provider or self hosted service
- [X] rTorrent Commit and OS version provided

### Tell us about your environment

rTorrrent Commit: v6 from release
OS: Ubuntu 22.04 LTS

### Tell us if rTorrent seedbox is self hosted or provided

Self hosted

### Describe the bug

After following the guide to compile rtorrent v6, it fails when trying to start. I am not sure where I should start looking. I tried switching out the config files, but that did not change anything. Tried full vanilla config file provided with v6, and also a modified one.

The error rTorrent puts out to terminal is: `rtorrent: symbol lookup error: rtorrent: undefined symbol: _ZN7torrent8Throttle12set_max_rateEm`

I'm hoping it doesnt stem from some random file somewhere on my system that I cannot locate. Please advice.

### Steps to reproduce

1. Get all sources
2. Compile and install
3. Try to run rTorrent 

### Expected behavior

Expect rTorrent to run, atleast give me a more concise error message that could point me in a direction

**Comment by stickz** [comment]
It didn't build or run properly. This is a libtorrent symbol. It's linking against the wrong version of libtorrent.

**Comment by jazha** [comment]
Got it running with removal of wrong version of libtorrent and recompiling. Had to do the same with the libxmlrpc. Thanks!
