### ISSUE TITLE
Error installing rTorrent - compilation terminated

### ISSUE THREAD

**Issue by 1DudeBud** [stickz/rtorrent#53]
### Please complete the following tasks.

- [X] Name of seedbox provider or self hosted service
- [X] rTorrent Commit and OS version provided

### Tell us about your environment

rTorrent Commit: https://github.com/stickz/rtorrent/commit/7e852c88465682864ef80d86f1d085d932ef3d89
OS: Ubuntu 22.04 LTS

### Tell us if rTorrent seedbox is self hosted or provided

Self hosted

### Describe the bug

Following the README steps; installing UDNS, installing xmlrpc-c (v1.60.xx), installing libtorrent, -the final install build; installing rTorrent, fails both with xmlrpc-c and LTO. 

### Steps to reproduce

1. Go to: https://github.com/stickz/rtorrent
2. Follow building steps; installing UDNS, installing xmlrpc-c (v1.60.xx), installing libtorrent
3. Installing rTorrent is where things stop working, I tried using both methods: configuring with xmlrpc-c
`cd ../rtorrent;\
./autogen.sh;\
./configure --prefix=/usr --with-xmlrpc-c --with-ncurses;\
make -j$(nproc) CXXFLAGS="-O3";\
make -j$(nproc) install;` 
and biulding with LTO
`make -j$(nproc) CXXFLAGS="-O3 -flto=\"$(nproc)\" -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing";`
Both created the error.

Terminal output:
`compilation terminated.
make[3]: *** [Makefile:457: curl_get.o] Error 1
make[3]: Leaving directory '/etc/stickz-rtorrent/rtorrent/src/core'
make[2]: *** [Makefile:634: all-recursive] Error 1
make[2]: Leaving directory '/etc/stickz-rtorrent/rtorrent/src'
make[1]: *** [Makefile:452: all-recursive] Error 1
make[1]: Leaving directory '/etc/stickz-rtorrent/rtorrent'
make: *** [Makefile:384: all] Error 2
`

Here is a longer version:

`make  all-recursive
make[1]: Entering directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent'
Making all in doc
make[2]: Entering directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/doc'
Making all in src
make[2]: Entering directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/src'
Making all in core
make[3]: Entering directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/src/core'
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -O3 -flto="24" -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -MT curl_get.o -MD -MP -MF .deps/curl_get.Tpo -c -o curl_get.o curl_get.cc
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -O3 -flto="24" -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -MT curl_socket.o -MD -MP -MF .deps/curl_socket.Tpo -c -o curl_socket.o curl_socket.cc
g++ -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -O3 -flto="24" -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -MT curl_stack.o -MD -MP -MF .deps/curl_stack.Tpo -c -o curl_stack.o curl_stack.cc
curl_socket.cc:39:10: fatal error: curl/curl.h: No such file or directory
   39 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:457: curl_socket.o] Error 1
make[3]: *** Waiting for unfinished jobs....
curl_stack.cc:40:10: fatal error: curl/multi.h: No such file or directory
   40 | #include <curl/multi.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:457: curl_stack.o] Error 1
curl_get.cc:40:10: fatal error: curl/curl.h: No such file or directory
   40 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:457: curl_get.o] Error 1
make[3]: Leaving directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/src/core'
make[2]: *** [Makefile:634: all-recursive] Error 1
make[2]: Leaving directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent/src'
make[1]: *** [Makefile:454: all-recursive] Error 1
make[1]: Leaving directory '/etc/stickz-rtorrent/rtorrent/stickz-rtorrent/rtorrent'
make: *** [Makefile:386: all] Error 2
`

### Expected behavior

I was hoping that the expected behavior was to be a successful rTorrent build.

### Additional context

For the record, this is my first ever bug report... and honestly I'm not even sure if this is really a bug, or if it is just me being a total n00b.  I'm learning as I go, so please don't destroy me if this is user error.   I relate my adventures in Linux to the words of the great philosopher _Jake the Dog_ as he taught me that "sucking at something is the first step to being sorta good at something" eventually...

**Comment by stickz** [comment]
Hello @1DudeBud, you are missing the curl header file required to compile rTorrent.

Please type the following command for Ubuntu 22.04 LTS.
`sudo apt install libcurl4-gnutls-dev`

Also, I made an installation script that may be easier for you to use given your experience.
https://github.com/stickz/rutorrent-rtorrent-build-scripts

**Comment by 1DudeBud** [comment]
Okay - Figured it out combing over other bug reports...
[https://github.com/stickz/rtorrent/issues/43](https://github.com/stickz/rtorrent/issues/43)

Thanks jazha, needed dev version of curl present.


Use the OpenSSL variant:
`sudo apt-get install libcurl4-openssl-dev`

Longer version of fix:
[https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory](url)

**Comment by 1DudeBud** [comment]
> Hello @1DudeBud, you are missing the curl header file required to compile rTorrent.
> 
> Please type the following command for Ubuntu 22.04 LTS. `sudo apt install libcurl4-gnutls-dev`
> 
> Also, I made an installation script that may be easier for you to use given your experience. https://github.com/stickz/rutorrent-rtorrent-build-scripts

Wow, Thanks for the super fast reply!
Just found the solution as you must've been typing. - Thanks again!
